import { PrismaClient } from "@prisma/client"

const prisma = new PrismaClient()

async function main() {
    console.log("Clearing existing bookings and cars...")

    await prisma.xpTransaction.deleteMany({})
    await prisma.review.deleteMany({})
    await prisma.transaction.deleteMany({})
    await prisma.carImage.deleteMany({})
    await prisma.product.deleteMany({})

    console.log("Seeding cars...")

    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    const cars: any[] = [
        // ── Compact ──────────────────────────────────────────────────────────
        {
            name: "Polo GTI",
            brand: "Volkswagen",
            model: "Polo",
            year: 2023,
            category: "Compact",
            description: "The Polo GTI blends everyday practicality with genuine hot-hatch excitement. Turbocharged 2.0 TSI engine, sharp handling and premium interior make it the perfect city companion.",
            pricePerDay: 55,
            deposit: 220,
            transmission: "Automatic",
            fuelType: "Petrol",
            seats: 5,
            horsepower: 207,
            drivetrain: "FWD",
            zeroToHundred: 6.5,
            topSpeed: 237,
            mileage: 12000,
            licensePlate: "VW-1234",
            location: "Budapest",
            featured: false,
            active: true,
            dailyKmLimit: 200,
            excessKmFee: 0.25,
            images: { create: [
                { url: "https://images.unsplash.com/photo-1503376780353-7e6692767b70?w=1200" },
                { url: "https://images.unsplash.com/photo-1494976388531-d1058494cdd8?w=1200" },
            ]},
        },
        {
            name: "Clio RS Line",
            brand: "Renault",
            model: "Clio",
            year: 2023,
            category: "Compact",
            description: "Stylish French flair in a compact package. The Clio RS Line features sport-tuned suspension, bold styling and a refined turbocharged engine for spirited urban driving.",
            pricePerDay: 48,
            deposit: 190,
            transmission: "Automatic",
            fuelType: "Hybrid",
            seats: 5,
            horsepower: 145,
            drivetrain: "FWD",
            zeroToHundred: 8.1,
            topSpeed: 205,
            mileage: 18000,
            licensePlate: "RN-5678",
            location: "Vienna",
            featured: false,
            active: true,
            dailyKmLimit: 200,
            excessKmFee: 0.20,
            images: { create: [
                { url: "https://images.unsplash.com/photo-1553440569-bcc63803a83d?w=1200" },
                { url: "https://images.unsplash.com/photo-1493238792000-8113da705763?w=1200" },
            ]},
        },

        // ── Sedan ─────────────────────────────────────────────────────────────
        {
            name: "3 Series",
            brand: "BMW",
            model: "3 Series",
            year: 2023,
            category: "Sedan",
            description: "The definitive executive sedan. The BMW 3 Series delivers legendary rear-wheel-drive dynamics, a beautifully crafted interior and cutting-edge iDrive technology in a perfectly balanced package.",
            pricePerDay: 120,
            deposit: 600,
            transmission: "Automatic",
            fuelType: "Petrol",
            seats: 5,
            horsepower: 255,
            drivetrain: "RWD",
            zeroToHundred: 5.8,
            topSpeed: 250,
            mileage: 15000,
            licensePlate: "BM-3001",
            location: "Budapest",
            featured: true,
            active: true,
            dailyKmLimit: 300,
            excessKmFee: 0.35,
            images: { create: [
                { url: "https://images.unsplash.com/photo-1555215695-3004980ad54e?w=1200" },
                { url: "https://images.unsplash.com/photo-1503736334956-4c8f8e92946d?w=1200" },
            ]},
        },
        {
            name: "C-Class",
            brand: "Mercedes",
            model: "C-Class",
            year: 2024,
            category: "Sedan",
            description: "Mercedes-Benz C-Class — where refined luxury meets spirited performance. The latest generation features a stunning interior with a portrait touchscreen, whisper-quiet ride and the iconic three-pointed star.",
            pricePerDay: 130,
            deposit: 650,
            transmission: "Automatic",
            fuelType: "Hybrid",
            seats: 5,
            horsepower: 258,
            drivetrain: "RWD",
            zeroToHundred: 6.0,
            topSpeed: 250,
            mileage: 9000,
            licensePlate: "MB-3002",
            location: "Vienna",
            featured: true,
            active: true,
            dailyKmLimit: 300,
            excessKmFee: 0.35,
            images: { create: [
                { url: "https://images.unsplash.com/photo-1618843479313-40f8afb4b4d8?w=1200" },
                { url: "https://images.unsplash.com/photo-1511919884226-fd3cad34687c?w=1200" },
            ]},
        },
        {
            name: "A4",
            brand: "Audi",
            model: "A4",
            year: 2023,
            category: "Sedan",
            description: "Audi A4 — understated elegance with Quattro all-wheel drive precision. A sophisticated business sedan with virtual cockpit, refined turbocharged engine and a cabin built to impress.",
            pricePerDay: 115,
            deposit: 580,
            transmission: "Automatic",
            fuelType: "Petrol",
            seats: 5,
            horsepower: 245,
            drivetrain: "AWD",
            zeroToHundred: 6.0,
            topSpeed: 250,
            mileage: 22000,
            licensePlate: "AU-4004",
            location: "Prague",
            featured: false,
            active: true,
            dailyKmLimit: 300,
            excessKmFee: 0.30,
            images: { create: [
                { url: "https://images.unsplash.com/photo-1606016159991-dfe4f2746ad5?w=1200" },
                { url: "https://images.unsplash.com/photo-1612825173281-9a193378527e?w=1200" },
            ]},
        },

        // ── SUV ───────────────────────────────────────────────────────────────
        {
            name: "X5",
            brand: "BMW",
            model: "X5",
            year: 2023,
            category: "SUV",
            description: "The BMW X5 xDrive redefines what an SUV can be — commanding road presence, athletic driving dynamics and a sumptuous interior with panoramic roof. Equally at home on mountain roads and motorways.",
            pricePerDay: 180,
            deposit: 900,
            transmission: "Automatic",
            fuelType: "Petrol",
            seats: 5,
            horsepower: 340,
            drivetrain: "AWD",
            zeroToHundred: 5.5,
            topSpeed: 250,
            mileage: 20000,
            licensePlate: "BM-5005",
            location: "Budapest",
            featured: true,
            active: true,
            dailyKmLimit: 350,
            excessKmFee: 0.40,
            images: { create: [
                { url: "https://images.unsplash.com/photo-1580273916550-e323be2ae537?w=1200" },
                { url: "https://images.unsplash.com/photo-1603584173870-7f23fdae1b7a?w=1200" },
            ]},
        },
        {
            name: "GLE 400d",
            brand: "Mercedes",
            model: "GLE",
            year: 2024,
            category: "SUV",
            description: "The Mercedes GLE 400d combines diesel efficiency with luxury SUV presence. Air suspension, MBUX infotainment and a beautifully appointed seven-seat cabin make every journey feel exceptional.",
            pricePerDay: 195,
            deposit: 980,
            transmission: "Automatic",
            fuelType: "Diesel",
            seats: 7,
            horsepower: 330,
            drivetrain: "AWD",
            zeroToHundred: 5.9,
            topSpeed: 250,
            mileage: 16000,
            licensePlate: "MB-6006",
            location: "Berlin",
            featured: true,
            active: true,
            dailyKmLimit: 400,
            excessKmFee: 0.40,
            images: { create: [
                { url: "https://images.unsplash.com/photo-1519641471654-76ce0107ad1b?w=1200" },
                { url: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=1200" },
            ]},
        },
        {
            name: "Q7",
            brand: "Audi",
            model: "Q7",
            year: 2023,
            category: "SUV",
            description: "Audi Q7 — the flagship SUV with 7-seat versatility and Quattro all-road capability. Matrix LED headlights, virtual cockpit plus and an air suspension system deliver first-class travel every time.",
            pricePerDay: 185,
            deposit: 920,
            transmission: "Automatic",
            fuelType: "Diesel",
            seats: 7,
            horsepower: 286,
            drivetrain: "AWD",
            zeroToHundred: 6.1,
            topSpeed: 250,
            mileage: 28000,
            licensePlate: "AU-7007",
            location: "Vienna",
            featured: false,
            active: true,
            dailyKmLimit: 400,
            excessKmFee: 0.40,
            images: { create: [
                { url: "https://images.unsplash.com/photo-1616422285623-13ff0162193c?w=1200" },
                { url: "https://images.unsplash.com/photo-1567818735868-e71b99932e29?w=1200" },
            ]},
        },

        // ── Sport ─────────────────────────────────────────────────────────────
        {
            name: "M4 Competition",
            brand: "BMW",
            model: "M4",
            year: 2023,
            category: "Sport",
            description: "The BMW M4 Competition is raw, focused and electrifying. 510 hp inline-six with M xDrive, active M suspension and a track-tuned chassis deliver supercar-baiting performance in an agile two-door package.",
            pricePerDay: 280,
            deposit: 1400,
            transmission: "Automatic",
            fuelType: "Petrol",
            seats: 4,
            horsepower: 510,
            drivetrain: "AWD",
            zeroToHundred: 3.5,
            topSpeed: 290,
            mileage: 8000,
            licensePlate: "BM-M401",
            location: "Budapest",
            featured: true,
            active: true,
            minimumAge: 25,
            minimumRentalDays: 2,
            dailyKmLimit: 250,
            excessKmFee: 0.60,
            images: { create: [
                { url: "https://images.unsplash.com/photo-1617814076367-b759c7d7e738?w=1200" },
                { url: "https://images.unsplash.com/photo-1592853625597-7d17c46c8016?w=1200" },
            ]},
        },
        {
            name: "AMG C63 S",
            brand: "Mercedes",
            model: "C63",
            year: 2023,
            category: "Sport",
            description: "Mercedes-AMG C63 S — 671 hp plug-in hybrid powerplant, thunderous exhaust note and AMG RIDE CONTROL+ suspension. This is the most powerful four-cylinder car in the world, and it sounds like a V8.",
            pricePerDay: 295,
            deposit: 1500,
            transmission: "Automatic",
            fuelType: "Hybrid",
            seats: 4,
            horsepower: 671,
            drivetrain: "RWD",
            zeroToHundred: 3.4,
            topSpeed: 280,
            mileage: 6000,
            licensePlate: "MB-C631",
            location: "Vienna",
            featured: true,
            active: true,
            minimumAge: 25,
            minimumRentalDays: 2,
            dailyKmLimit: 250,
            excessKmFee: 0.65,
            images: { create: [
                { url: "https://images.unsplash.com/photo-1609521263047-f8f205293f24?w=1200" },
                { url: "https://images.unsplash.com/photo-1549317661-bd32c8ce0db2?w=1200" },
            ]},
        },
        {
            name: "RS5 Sportback",
            brand: "Audi",
            model: "RS5",
            year: 2023,
            category: "Sport",
            description: "Audi RS5 Sportback — 450 hp biturbo V6 with Quattro all-wheel drive and sport differential. Five doors of practicality wrapped in an aggressively styled body that hides astonishing everyday performance.",
            pricePerDay: 270,
            deposit: 1350,
            transmission: "Automatic",
            fuelType: "Petrol",
            seats: 5,
            horsepower: 450,
            drivetrain: "AWD",
            zeroToHundred: 3.9,
            topSpeed: 280,
            mileage: 11000,
            licensePlate: "AU-RS51",
            location: "Berlin",
            featured: false,
            active: true,
            minimumAge: 25,
            minimumRentalDays: 2,
            dailyKmLimit: 250,
            excessKmFee: 0.55,
            images: { create: [
                { url: "https://images.unsplash.com/photo-1541443131876-44b03de101c5?w=1200" },
                { url: "https://images.unsplash.com/photo-1555215695-3004980ad54e?w=1200" },
            ]},
        },

        // ── Premium ───────────────────────────────────────────────────────────
        {
            name: "7 Series",
            brand: "BMW",
            model: "7 Series",
            year: 2024,
            category: "Premium",
            description: "The BMW 7 Series redefines long-distance luxury. Theatre Screen in the rear, Executive Lounge seating, 31″ 8K display and a plug-in V8 hybrid drivetrain — this is the pinnacle of automotive technology.",
            pricePerDay: 320,
            deposit: 1600,
            transmission: "Automatic",
            fuelType: "Hybrid",
            seats: 5,
            horsepower: 544,
            drivetrain: "AWD",
            zeroToHundred: 4.7,
            topSpeed: 250,
            mileage: 7000,
            licensePlate: "BM-7001",
            location: "Budapest",
            featured: true,
            active: true,
            minimumAge: 25,
            minimumRentalDays: 2,
            dailyKmLimit: 400,
            excessKmFee: 0.50,
            images: { create: [
                { url: "https://images.unsplash.com/photo-1523983302500-a84da543c48b?w=1200" },
                { url: "https://images.unsplash.com/photo-1552519507-da3b142c6e3d?w=1200" },
            ]},
        },
        {
            name: "S-Class",
            brand: "Mercedes",
            model: "S-Class",
            year: 2024,
            category: "Premium",
            description: "The Mercedes-Benz S-Class — the world's most sophisticated sedan. Rear-axle steering, E-Active Body Control, Burmester 4D surround sound and Augmented Reality HUD define a new standard of automotive excellence.",
            pricePerDay: 380,
            deposit: 1900,
            transmission: "Automatic",
            fuelType: "Hybrid",
            seats: 5,
            horsepower: 510,
            drivetrain: "AWD",
            zeroToHundred: 4.9,
            topSpeed: 250,
            mileage: 5000,
            licensePlate: "MB-S001",
            location: "Vienna",
            featured: true,
            active: true,
            minimumAge: 28,
            minimumRentalDays: 2,
            dailyKmLimit: 400,
            excessKmFee: 0.55,
            images: { create: [
                { url: "https://images.unsplash.com/photo-1631295868223-63265b40d9e4?w=1200" },
                { url: "https://images.unsplash.com/photo-1624391563660-e8a00a1e9e8b?w=1200" },
            ]},
        },

        // ── Luxury ────────────────────────────────────────────────────────────
        {
            name: "Ghost",
            brand: "Rolls-Royce",
            model: "Ghost",
            year: 2023,
            category: "Luxury",
            description: "The Rolls-Royce Ghost Series II — post opulence in its purest form. Architecture of Luxury insulation, a starlight headliner with 1,340 fibre-optic stars and a 6.75-litre twin-turbo V12. Pure serenity at any speed.",
            pricePerDay: 1200,
            deposit: 8000,
            transmission: "Automatic",
            fuelType: "Petrol",
            seats: 5,
            horsepower: 571,
            drivetrain: "AWD",
            zeroToHundred: 4.8,
            topSpeed: 250,
            mileage: 4000,
            licensePlate: "RR-GH01",
            location: "Budapest",
            featured: true,
            active: true,
            minimumAge: 30,
            minimumRentalDays: 3,
            dailyKmLimit: 200,
            excessKmFee: 2.00,
            images: { create: [
                { url: "https://images.unsplash.com/photo-1631295868223-63265b40d9e4?w=1200" },
                { url: "https://images.unsplash.com/photo-1526726538690-5cbf956ae2fd?w=1200" },
            ]},
        },
        {
            name: "Continental GT",
            brand: "Bentley",
            model: "Continental",
            year: 2023,
            category: "Luxury",
            description: "The Bentley Continental GT V8 — handcrafted grand touring perfection. Rotating veneer dashboard, 650 hp V8 thunder and a chassis that floats over broken road while remaining dynamically brilliant.",
            pricePerDay: 950,
            deposit: 6000,
            transmission: "Automatic",
            fuelType: "Petrol",
            seats: 4,
            horsepower: 550,
            drivetrain: "AWD",
            zeroToHundred: 4.0,
            topSpeed: 318,
            mileage: 6000,
            licensePlate: "BT-CG01",
            location: "Vienna",
            featured: true,
            active: true,
            minimumAge: 28,
            minimumRentalDays: 3,
            dailyKmLimit: 250,
            excessKmFee: 1.50,
            images: { create: [
                { url: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=1200" },
                { url: "https://images.unsplash.com/photo-1567818735868-e71b99932e29?w=1200" },
            ]},
        },
        {
            name: "Panamera Turbo S",
            brand: "Porsche",
            model: "Panamera",
            year: 2024,
            category: "Luxury",
            description: "The Porsche Panamera Turbo S E-Hybrid — the four-door sports car. 700 hp combined, active aerodynamics, rear-axle steering and a Burmester High-End 3D sound system. Nothing compromises, nothing competes.",
            pricePerDay: 750,
            deposit: 4500,
            transmission: "Automatic",
            fuelType: "Hybrid",
            seats: 4,
            horsepower: 700,
            drivetrain: "AWD",
            zeroToHundred: 3.2,
            topSpeed: 315,
            mileage: 3500,
            licensePlate: "PO-PA01",
            location: "Berlin",
            featured: true,
            active: true,
            minimumAge: 28,
            minimumRentalDays: 2,
            dailyKmLimit: 300,
            excessKmFee: 1.20,
            images: { create: [
                { url: "https://images.unsplash.com/photo-1544636331-e26879cd4d9b?w=1200" },
                { url: "https://images.unsplash.com/photo-1503376780353-7e6692767b70?w=1200" },
            ]},
        },

        // ── Supercar ──────────────────────────────────────────────────────────
        {
            name: "911 Turbo S",
            brand: "Porsche",
            model: "911",
            year: 2024,
            category: "Supercar",
            description: "The Porsche 911 Turbo S — 650 hp twin-turbo flat-six, Porsche Traction Management with PDCC Sport and launch control. 0–100 in 2.7 seconds. Seven decades of engineering excellence condensed into an icon.",
            pricePerDay: 890,
            deposit: 5500,
            transmission: "Automatic",
            fuelType: "Petrol",
            seats: 4,
            horsepower: 650,
            drivetrain: "AWD",
            zeroToHundred: 2.7,
            topSpeed: 330,
            mileage: 4500,
            licensePlate: "PO-9T01",
            location: "Budapest",
            featured: true,
            active: true,
            minimumAge: 28,
            minimumRentalDays: 2,
            dailyKmLimit: 200,
            excessKmFee: 1.80,
            images: { create: [
                { url: "https://images.unsplash.com/photo-1544636331-e26879cd4d9b?w=1200" },
                { url: "https://images.unsplash.com/photo-1503376780353-7e6692767b70?w=1200" },
            ]},
        },
        {
            name: "Huracan EVO",
            brand: "Lamborghini",
            model: "Huracan",
            year: 2023,
            category: "Supercar",
            description: "The Lamborghini Huracan EVO — naturally aspirated 5.2-litre V10 screaming to 8,500 rpm. LDVI predictive all-wheel drive, magnetorheological suspension and a soundtrack that turns heads for miles.",
            pricePerDay: 1100,
            deposit: 7000,
            transmission: "Automatic",
            fuelType: "Petrol",
            seats: 2,
            horsepower: 640,
            drivetrain: "AWD",
            zeroToHundred: 2.9,
            topSpeed: 325,
            mileage: 5500,
            licensePlate: "LB-HE01",
            location: "Budapest",
            featured: true,
            active: true,
            minimumAge: 30,
            minimumRentalDays: 2,
            dailyKmLimit: 150,
            excessKmFee: 2.50,
            images: { create: [
                { url: "https://images.unsplash.com/photo-1545558014-8692077e9b5c?w=1200" },
                { url: "https://images.unsplash.com/photo-1526726538690-5cbf956ae2fd?w=1200" },
            ]},
        },
        {
            name: "F8 Tributo",
            brand: "Ferrari",
            model: "F8",
            year: 2023,
            category: "Supercar",
            description: "The Ferrari F8 Tributo — 710 hp twin-turbo V8, active aerodynamics inherited from the FXX K and Ferrari Dynamic Enhancer. A mid-engine masterpiece that is simultaneously race car and daily supercar.",
            pricePerDay: 1250,
            deposit: 8000,
            transmission: "Automatic",
            fuelType: "Petrol",
            seats: 2,
            horsepower: 710,
            drivetrain: "RWD",
            zeroToHundred: 2.9,
            topSpeed: 340,
            mileage: 3200,
            licensePlate: "FR-F801",
            location: "Vienna",
            featured: true,
            active: true,
            minimumAge: 30,
            minimumRentalDays: 2,
            dailyKmLimit: 150,
            excessKmFee: 2.80,
            images: { create: [
                { url: "https://images.unsplash.com/photo-1592853625597-7d17c46c8016?w=1200" },
                { url: "https://images.unsplash.com/photo-1617814076367-b759c7d7e738?w=1200" },
            ]},
        },
        {
            name: "Artura",
            brand: "McLaren",
            model: "Artura",
            year: 2024,
            category: "Supercar",
            description: "The McLaren Artura — a new era of McLaren performance. Plug-in V6 hybrid, 680 hp, carbon fibre MonoCell II chassis and the pure driver focus that defines every McLaren. Thunderous, efficient, extraordinary.",
            pricePerDay: 1150,
            deposit: 7500,
            transmission: "Automatic",
            fuelType: "Hybrid",
            seats: 2,
            horsepower: 680,
            drivetrain: "RWD",
            zeroToHundred: 3.0,
            topSpeed: 330,
            mileage: 2800,
            licensePlate: "MC-AR01",
            location: "Prague",
            featured: false,
            active: true,
            minimumAge: 30,
            minimumRentalDays: 2,
            dailyKmLimit: 150,
            excessKmFee: 2.60,
            images: { create: [
                { url: "https://images.unsplash.com/photo-1566473965997-3de9c817e938?w=1200" },
                { url: "https://images.unsplash.com/photo-1493238792000-8113da705763?w=1200" },
            ]},
        },

        // ── Hypercar ──────────────────────────────────────────────────────────
        {
            name: "SF90 Stradale",
            brand: "Ferrari",
            model: "SF90",
            year: 2024,
            category: "Hypercar",
            description: "The Ferrari SF90 Stradale — Ferrari's most powerful production car ever. 1,000 hp tri-motor hybrid system, eAWD, MGU-K kinetic energy recovery and 0–100 in 2.5 seconds. The future of the prancing horse.",
            pricePerDay: 2500,
            deposit: 15000,
            transmission: "Automatic",
            fuelType: "Hybrid",
            seats: 2,
            horsepower: 1000,
            drivetrain: "AWD",
            zeroToHundred: 2.5,
            topSpeed: 340,
            mileage: 1800,
            licensePlate: "FR-SF01",
            location: "Budapest",
            featured: true,
            active: true,
            minimumAge: 32,
            minimumRentalDays: 3,
            dailyKmLimit: 100,
            excessKmFee: 5.00,
            images: { create: [
                { url: "https://images.unsplash.com/photo-1592853625597-7d17c46c8016?w=1200" },
                { url: "https://images.unsplash.com/photo-1544636331-e26879cd4d9b?w=1200" },
            ]},
        },
        {
            name: "Revuelto",
            brand: "Lamborghini",
            model: "Revuelto",
            year: 2024,
            category: "Hypercar",
            description: "The Lamborghini Revuelto — successor to the Aventador, powered by a 1,001 hp V12 hybrid. Three electric motors, sequential gear shifts in 0.2 ms and active aerodynamics that generate 35% more downforce than its predecessor.",
            pricePerDay: 3200,
            deposit: 20000,
            transmission: "Automatic",
            fuelType: "Hybrid",
            seats: 2,
            horsepower: 1001,
            drivetrain: "AWD",
            zeroToHundred: 2.5,
            topSpeed: 350,
            mileage: 900,
            licensePlate: "LB-RV01",
            location: "Vienna",
            featured: true,
            active: true,
            minimumAge: 32,
            minimumRentalDays: 3,
            dailyKmLimit: 100,
            excessKmFee: 6.00,
            images: { create: [
                { url: "https://images.unsplash.com/photo-1545558014-8692077e9b5c?w=1200" },
                { url: "https://images.unsplash.com/photo-1526726538690-5cbf956ae2fd?w=1200" },
            ]},
        },
    ]

    for (const data of cars) {
        await prisma.product.create({ data })
    }

    console.log(`Seeded ${cars.length} cars.`)
}

main()
    .catch((e) => {
        console.error(e)
        process.exit(1)
    })
    .finally(async () => {
        await prisma.$disconnect()
    })
